# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hopter < Formula
  desc "Self-hosted remote control plane for local coding agents"
  homepage "https://github.com/sorcererxw/hopter"
  version "0.0.39"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorcererxw/hopter/releases/download/v0.0.39/hopter-homebrew-darwin-amd64"
      sha256 "9f8157723c7ed2f60132b3b754ce5317aa8f2484a54c34aeb22fd08409b4dcb5"

      define_method(:install) do
        source = Dir["hopter-homebrew-*"].first
        bin.install source => "hopter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorcererxw/hopter/releases/download/v0.0.39/hopter-homebrew-darwin-arm64"
      sha256 "1d6bfa80710149ff643dad857a8dc2c49e370a9157a173d7ce744885f4a8f3fd"

      define_method(:install) do
        source = Dir["hopter-homebrew-*"].first
        bin.install source => "hopter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorcererxw/hopter/releases/download/v0.0.39/hopter-homebrew-linux-amd64"
      sha256 "432cb799293781d047bea36065212365bf678999f9c495ed683335a8dfd30c1b"
      define_method(:install) do
        source = Dir["hopter-homebrew-*"].first
        bin.install source => "hopter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorcererxw/hopter/releases/download/v0.0.39/hopter-homebrew-linux-arm64"
      sha256 "ae776382e3bde6ec8ddce09128447b88efedf1f9cfb5951ac5db67c5385f2868"
      define_method(:install) do
        source = Dir["hopter-homebrew-*"].first
        bin.install source => "hopter"
      end
    end
  end

  service do
    run [opt_bin/"hopter", "server"]
    keep_alive true
    log_path var/"log/hopter.log"
    error_log_path var/"log/hopter.err.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hopter version")
  end
end
