# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hopter < Formula
  desc "Self-hosted remote control plane for local coding agents"
  homepage "https://github.com/sorcererxw/hopter"
  version "0.0.40"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorcererxw/hopter/releases/download/v0.0.40/hopter-homebrew-darwin-amd64"
      sha256 "dbb4cd2a21418a59cabdc66eb889872159756b79fd835c5e407c45273b9ff8e9"

      define_method(:install) do
        source = Dir["hopter-homebrew-*"].first
        bin.install source => "hopter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorcererxw/hopter/releases/download/v0.0.40/hopter-homebrew-darwin-arm64"
      sha256 "42f062f15ba2761c829e34f0fea61c99199482fb4606eeef2cca6977f410d6b1"

      define_method(:install) do
        source = Dir["hopter-homebrew-*"].first
        bin.install source => "hopter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorcererxw/hopter/releases/download/v0.0.40/hopter-homebrew-linux-amd64"
      sha256 "aa752fbe5ccc5fff04f78a544218096e509a3b915fed3c6b8bf4c0b4de00087b"
      define_method(:install) do
        source = Dir["hopter-homebrew-*"].first
        bin.install source => "hopter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorcererxw/hopter/releases/download/v0.0.40/hopter-homebrew-linux-arm64"
      sha256 "fe98ad9197093f989974ca24d7db07062977275b9903b158d61d4d8d9d7dd344"
      define_method(:install) do
        source = Dir["hopter-homebrew-*"].first
        bin.install source => "hopter"
      end
    end
  end

  service do
    run [opt_bin/"hopter", "server"]
    keep_alive true
    log_path var/"log/hopter.log"
    error_log_path var/"log/hopter.err.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hopter version")
  end
end
