# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hopter < Formula
  desc "Self-hosted remote control plane for local coding agents"
  homepage "https://github.com/sorcererxw/hopter"
  version "0.0.37"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sorcererxw/hopter/releases/download/v0.0.37/hopter-homebrew-darwin-amd64"
      sha256 "cc890b3b9e294e42cadf9d6816202ddcbf00a44e8afcac477ac3ae4ed2fdc45d"

      define_method(:install) do
        source = Dir["hopter-homebrew-*"].first
        bin.install source => "hopter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sorcererxw/hopter/releases/download/v0.0.37/hopter-homebrew-darwin-arm64"
      sha256 "8036bdf7d4827a16bf95d511a6a4880b53ea2676b8c7ccc87a7d8706e8e334f0"

      define_method(:install) do
        source = Dir["hopter-homebrew-*"].first
        bin.install source => "hopter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorcererxw/hopter/releases/download/v0.0.37/hopter-homebrew-linux-amd64"
      sha256 "0078b7e01520edd664b96ca8830a81fa30c497f6fbab4c7b65088c460cc66963"
      define_method(:install) do
        source = Dir["hopter-homebrew-*"].first
        bin.install source => "hopter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sorcererxw/hopter/releases/download/v0.0.37/hopter-homebrew-linux-arm64"
      sha256 "476ca3e18d6050b0a32dff5b517ae9de46377e40010f2e9b21e8b4ae73cea209"
      define_method(:install) do
        source = Dir["hopter-homebrew-*"].first
        bin.install source => "hopter"
      end
    end
  end

  service do
    run [opt_bin/"hopter", "server"]
    keep_alive true
    log_path var/"log/hopter.log"
    error_log_path var/"log/hopter.err.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hopter version")
  end
end
